'''
Polling places

Utilities
'''

import json
import random
import sys

# DO NOT REMOVE THESE LINES OF CODE
# pylint: disable-msg= invalid-name, too-many-arguments, line-too-long
# pylint: disable-msg= too-many-branches

def gen_poisson_voter_parameters(arrival_rate, voting_duration_rate):
    '''
    Draw gap and voting duration from exponetial distribution

    Inputs:
        arrival_rate: (float) lambda for gap
        voting_duration_rate: (float) lambda for voting duration

    Returns:
        (gap, voting duration) as a pair of floats
    '''
    return (random.expovariate(arrival_rate),
            random.expovariate(voting_duration_rate))


def load_precincts(precincts_filename):
    '''
    Load a precincts file.

    Inputs:
        precincts_filename: (string) name of the precincts file

    Returns:
        A tuple containing:
        - a list of precinct dictionaries
        - a seed (integer)
    '''

    try:
        config = json.load(open(precincts_filename))
    except OSError as e:
        print("{}".format(e), file=sys.stderr)
        return None

    if not isinstance(config, dict):
        raise ValueError("Configuration file syntax error: should contain a JSON object")

    # Validate seed
    if "seed" not in config or not isinstance(config["seed"], int):
        raise ValueError("Configuration file syntax error: does not contain a seed")

    # Validate precincts
    if "precincts" not in config or not isinstance(config["precincts"], list):
        raise ValueError("Configuration file syntax error: does not contain a list of precincts")

    if config["precincts"] == []:
        raise ValueError("Configuration file must contain at least one precinct")

    for p in config["precincts"]:
        if not isinstance(p, dict):
            raise ValueError("List of precincts includes an unexpected value: {}".format(p))

        if "name" not in p:
            raise ValueError("Precinct is missing 'name' field: {}".format(p))

        for f in ("hours_open", "num_booths", "num_voters", "voter_distribution"):
            if f not in p:
                raise ValueError("Precinct {} is missing '{}' field".format(p["name"], f))

        if "type" not in p["voter_distribution"]:
            raise ValueError("Precinct {} is missing 'type' field in 'voter_distribution'".format(p["name"]))

        if p["voter_distribution"]["type"] == "poisson":
            for f in ("voting_duration_rate", "arrival_rate"):
                if f not in p["voter_distribution"]:
                    raise ValueError("Precinct {} is missing '{}' field in 'voter_distribution".format(p["name"], f))
        else:
            raise ValueError("Precinct {} has an unknown voter distribution '{}".format(p["name"], p["voter_distribution"]))

    return config["precincts"], config["seed"]


def print_voters(voters, filename=None):
    '''
    Print the voters generated by the simulation.

    Inputs:
      voters: a list of voter objects
      filename: (string) specifies the name of a file to use,
         if included.
    '''
    if filename is None:
        file = sys.stdout
    else:
        try:
            file = open(filename, "w")
        except OSError as e:
            print(e, file=sys.stderr)
            sys.exit(1)

    print("Arrival Time   Voting Duration   Start Time    Departure Time",
          file=file)
    for v in voters:
        s = "{:10.2f}"
        none_str = "      None"
        at = s.format(v.arrival_time) if v.arrival_time else none_str
        vd = s.format(v.voting_duration) if v.voting_duration else none_str
        st = s.format(v.start_time) if v.start_time else none_str
        if v.arrival_time is None or \
           v.voting_duration is None or \
           v.start_time is None:
            dt = none_str
        else:
            dt = s.format(v.start_time + v.voting_duration)
        combined = "{}   {}       {}        {}\n"
        print(combined.format(at, vd, st, dt), file=file)
